### ISSUE TITLE
All effects are not functioning 

### ISSUE THREAD

**Issue by potato7YT** [ItsPi3141/discord-fake-avatar-decorations#3]
![Screenshot_2024-06-27-22-08-56-09_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/ItsPi3141/discord-fake-avatar-decorations/assets/85459992/2275c163-06c9-4037-b0ad-6fcc724225b4)
![Screenshot_2024-06-27-22-07-57-45_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/ItsPi3141/discord-fake-avatar-decorations/assets/85459992/d916caa8-cb0b-4ca1-85aa-b64c485671b2)

**Comment by ItsPi3141** [comment]
By "not functioning", do you mean they are the wrong size? If so, I've just fixed it.

**Comment by potato7YT** [comment]
> By "not functioning", do you mean they are the wrong size? If so, I've just fixed it.

Yes that what i mean 
But the error still remains 
![Screenshot_2024-06-27-22-31-19-86_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/ItsPi3141/discord-fake-avatar-decorations/assets/85459992/00f2c7c1-50db-4dd0-8781-75b2448273e9)

**Comment by potato7YT** [comment]
Never mind it works now
Can you look at my other issue @ItsPi3141
